<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MySolution.Email.Application\MySolution.Email.Application.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
      <PackageReference Include="MediatR" Version="14.2.0" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.10" />
      <PackageReference Include="Scriban" Version="7.2.5" />
      <PackageReference Include="SendGrid" Version="9.29.3" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Templates\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
