
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9"/>
        <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MySolution.Email.Application\MySolution.Email.Application.csproj" />
      <ProjectReference Include="..\MySolution.Email.Infrastructure\MySolution.Email.Infrastructure.csproj" />
    </ItemGroup>

</Project>
